apiVersion: v1
appVersion: 0.7.2
description: MetalLB is a load-balancer implementation for bare metal Kubernetes clusters By K.Yamato
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo.png
keywords:
- load-balancer
- balancer
- lb
- bgp
- arp
- vrrp
- vip
maintainers:
- email: kyamato@idcf.jp
  name: kyamato
name: metallb
version: 0.7.2
